/**
 * Generates the printed QR code for a campaign, with the Coltivio mark in the centre.
 *
 *   node scripts/generate-qr.mjs bioaktuell
 *
 * Writes an SVG and a 2400 px PNG to the brand asset folder of the monorepo. These are
 * print deliverables, not website assets, which is why they do not live in this repo.
 *
 * The mark in the middle only works because the code is generated at error correction
 * level H: 30 percent of the data is recoverable, and the knockout covers well under
 * ten percent. Do not lower the level and do not enlarge the logo.
 *
 * qrcode is pulled through `pnpm dlx` rather than added as a dependency, the same way
 * this repo already handles TypeScript. Nothing here runs during a site build.
 */
import { execFileSync } from 'node:child_process'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import sharp from 'sharp'

const scriptDir = path.dirname(fileURLToPath(import.meta.url))
const repoRoot = path.resolve(scriptDir, '..')
const monorepoRoot = path.resolve(repoRoot, '..')

const BASE_URL = 'https://coltivio.ch/go'
const LOGO = path.join(monorepoRoot, 'assets', 'logo', 'seperated', 'logo-mark.svg')
const OUT_DIR = path.join(monorepoRoot, 'assets', 'qr')

// The dark end of the brand gradient. Contrast against white is far above what any
// scanner needs. If a printer ever complains, '000000' is the escape hatch.
const DARK = '2b525a'
const LIGHT = 'ffffff'

// Fractions of the code's edge length. The knockout is what buys the logo its breathing
// room, the logo itself stays smaller so it never touches a module.
const KNOCKOUT = 0.24
const LOGO_SIZE = 0.19

const ref = process.argv[2]
if (!ref || !/^[a-z0-9-]{1,40}$/.test(ref)) {
  console.error('Usage: node scripts/generate-qr.mjs <ref>')
  console.error('  <ref> is lowercase letters, digits and hyphens, e.g. bioaktuell')
  process.exit(1)
}

const url = `${BASE_URL}/${ref}`

// 1. The raw code. Quiet zone 4 modules is the spec minimum and the reason a code still
//    scans off a busy magazine page.
const tmp = path.join(os.tmpdir(), `coltivio-qr-${ref}-${Date.now()}.svg`)
// Node refuses to spawn a .cmd shim without a shell, so on Windows the arguments have to
// be quoted by hand. Paths with spaces are the reason this is not left to chance.
const viaShell = process.platform === 'win32'
const arg = (value) => (viaShell ? `"${value}"` : value)
execFileSync(
  viaShell ? 'pnpm.cmd' : 'pnpm',
  ['dlx', 'qrcode@1.5.4', '-e', 'H', '-q', '4', '-t', 'svg', '-d', DARK, '-l', LIGHT, '-o', tmp, url].map(arg),
  { stdio: ['ignore', 'ignore', 'inherit'], shell: viaShell },
)
const raw = fs.readFileSync(tmp, 'utf8')
fs.unlinkSync(tmp)

const viewBox = raw.match(/viewBox="0 0 (\d+(?:\.\d+)?) /)
if (!viewBox) throw new Error('could not read the viewBox from the generated QR code')
const size = Number(viewBox[1])

const inner = raw.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '')

// 2. The mark, inlined as vector. Its ids and class names are prefixed so the file can be
//    dropped into a layout next to other SVGs without the gradients bleeding across.
const markSource = fs.readFileSync(LOGO, 'utf8')
const mark = markSource
  .replace(/^[\s\S]*?<svg[^>]*>/, '')
  .replace(/<\/svg>\s*$/, '')
  .replace(/linear-gradient/g, 'qr-mark-gradient')
  .replace(/cls-/g, 'qr-mark-cls-')

const markViewBox = markSource.match(/viewBox="0 0 (\d+(?:\.\d+)?) /)
if (!markViewBox) throw new Error('could not read the viewBox from the logo mark')
const markSize = Number(markViewBox[1])

const knockoutSide = size * KNOCKOUT
const knockoutPos = (size - knockoutSide) / 2
const logoSide = size * LOGO_SIZE
const logoPos = (size - logoSide) / 2
const logoScale = logoSide / markSize

const svg = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Coltivio QR code for ${url}. Generated by coltivio-landing/scripts/generate-qr.mjs -->
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 ${size} ${size}" width="${size}" height="${size}">
${inner.trim()}
  <rect x="${knockoutPos.toFixed(3)}" y="${knockoutPos.toFixed(3)}" width="${knockoutSide.toFixed(3)}" height="${knockoutSide.toFixed(3)}" rx="${(knockoutSide * 0.18).toFixed(3)}" fill="#${LIGHT}"/>
  <g transform="translate(${logoPos.toFixed(3)} ${logoPos.toFixed(3)}) scale(${logoScale.toFixed(6)})">
${mark.trim()}
  </g>
</svg>
`

fs.mkdirSync(OUT_DIR, { recursive: true })
const svgPath = path.join(OUT_DIR, `coltivio-go-${ref}.svg`)
const pngPath = path.join(OUT_DIR, `coltivio-go-${ref}.png`)
fs.writeFileSync(svgPath, svg)

// 3. A raster fallback, because editorial teams usually ask for one. 2400 px is 300 dpi
//    at 20 cm, far more than any print size this will ever get.
await sharp(Buffer.from(svg)).resize(2400, 2400).png().toFile(pngPath)

console.log(`URL      ${url}`)
console.log(`modules  ${size} (including the 4 module quiet zone)`)
console.log(`SVG      ${svgPath}`)
console.log(`PNG      ${pngPath}`)
